name: Build macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build macOS
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Xcode version
      run: sudo xcode-select -s /Applications/Xcode_15.3.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
